In [5]:
import pandas as pd
import numpy as np
import os
import ast

In [21]:
original_movies_metadata_df = pd.read_csv('..\Data\movies_metadata.csv')
original_movies_metadata_df.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\user\AppData\Local\Temp\ipykernel_3008\2827645161.py:1: SyntaxWarning: invalid escape sequence '\D'
  original_movies_metadata_df = pd.read_csv('..\Data\movies_metadata.csv')
C:\Users\user\AppData\Local\Temp\ipykernel_3008\2827645161.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  original_movies_metadata_df = pd.read_csv('..\Data\movies_metadata.csv')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [23]:
original_movies_metadata_df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [24]:
original_keywords_df = pd.read_csv('..\Data\keywords.csv')
original_keywords_df.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\user\AppData\Local\Temp\ipykernel_3008\3689338197.py:1: SyntaxWarning: invalid escape sequence '\D'
  original_keywords_df = pd.read_csv('..\Data\keywords.csv')

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [25]:
original_credits_df = pd.read_csv('..\Data\credits.csv')
original_credits_df.head()

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\user\AppData\Local\Temp\ipykernel_3008\1922261270.py:1: SyntaxWarning: invalid escape sequence '\D'
  original_credits_df = pd.read_csv('..\Data\credits.csv')

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [26]:
original_movies_metadata_df['id'] = pd.to_numeric(original_movies_metadata_df['id'], errors='coerce')

movies_df = original_movies_metadata_df.dropna(subset=['id'])
print(movies_df.shape)

movies_df['id'] = movies_df['id'].astype('int64')

movies = original_movies_metadata_df.merge(original_credits_df, on='id')
movies = movies.merge(original_keywords_df, on='id')

movies.shape

(45463, 24)

C:\Users\user\AppData\Local\Temp\ipykernel_3008\882405593.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['id'] = movies_df['id'].astype('int64')

(46628, 27)

In [27]:
movies = movies[['id', 'title', 'genres', 'overview', 'popularity', 'release_date', 'tagline', 'cast', 'crew', 'keywords', 'vote_average', 'vote_count', 'poster_path', 'imdb_id']]
movies['tagline'].fillna('', inplace=True)
movies['popularity'].fillna(0, inplace=True)
movies['vote_average'].fillna(0, inplace=True)
movies['vote_count'].fillna(0, inplace=True)
movies.head(100)

C:\Users\user\AppData\Local\Temp\ipykernel_3008\1016907411.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies['tagline'].fillna('', inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_3008\1016907411.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies['popularity'].fillna(0, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_3008\1016907411.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies['vote_average'].fillna(0, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_3008\1016907411.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies['vote_count'].fillna(0, inplace=True)

,id,title,genres,overview,popularity,release_date,tagline,cast,crew,keywords,vote_average,vote_count,poster_path,imdb_id
0,862.0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",7.7,5415.0,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,tt0114709
1,8844.0,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,Roll the dice and unleash the excitement!,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",6.9,2413.0,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,tt0113497
2,15602.0,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,11.7129,1995-12-22,Still Yelling. Still Fighting. Still Ready for...,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",6.5,92.0,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,tt0113228
3,31357.0,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,Friends are the people who let you be yourself...,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",6.1,34.0,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,tt0114885
4,11862.0,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,8.387519,1995-02-10,Just When His World Is Back To Normal... He's ...,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",5.7,173.0,/e64sOI48hQXyru7naBFyssKFxVd.jpg,tt0113041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,406.0,La Haine,"[{'id': 18, 'name': 'Drama'}]",Aimlessly whiling away their days in the concr...,12.108196,1995-05-31,Three Young Friends... One Last Chance.,"[{'cast_id': 2, 'character': 'Vinz', 'credit_i...","[{'credit_id': '52fe423fc3a36847f800f88b', 'de...","[{'id': 90, 'name': 'paris'}, {'id': 376, 'nam...",7.9,695.0,/jTzBED0leGPwWDqNewye11qzJgd.jpg,tt0113247
96,45549.0,Shopping,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","A dark, hip, urban story of a barren and anony...",2.657647,1994-12-06,No one leaves without paying...,"[{'cast_id': 1, 'character': 'Jo', 'credit_id'...","[{'credit_id': '52fe46c8c3a36847f8111c21', 'de...",[],5.6,13.0,/jdYL6f0KXnYBcnWnwGtnanJtKlE.jpg,tt0111173
97,63076.0,Heidi Fleiss: Hollywood Madam,"[{'id': 99, 'name': 'Documentary'}]",A documentary crew from the BBC arrives in L.A...,0.638211,1995-12-27,,"[{'cast_id': 2, 'character': 'Narrator', 'cred...","[{'credit_id': '52fe469ac3a368484e099bcb', 'de...","[{'id': 2398, 'name': 'narration'}, {'id': 123...",6.8,4.0,/j9k3UTx7OZ0xoCws1oACYQZFF5N.jpg,tt0113283
98,11062.0,City Hall,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",The accidental shooting of a boy in New York l...,4.807223,1996-02-16,It started with a shootout on a rainswept stre...,"[{'cast_id': 1, 'character': 'Mayor John Pappa...","[{'credit_id': '571fb8ccc3a368775b0032ff', 'de...","[{'id': 417, 'name': 'corruption'}, {'id': 156...",6.0,67.0,/ttdjD9NpxXsTJidPT3o1Gk0oTkG.jpg,tt0115907
99,13685.0,Bottle Rocket,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",Upon his release from a mental hospital follow...,6.904831,1996-02-21,"They're not really criminals, but everyone's g...","[{'cast_id': 1, 'character': 'Anthony Adams', ...","[{'credit_id': '52fe458b9251416c7505a35b', 'de...","[{'id': 380, 'name': 'brother brother relation...",6.8,285.0,/iuO10cRKrMfql5yc8YTgdfHt7gR.jpg,tt0115734

In [28]:
movies.shape

(46628, 14)

In [32]:
unique_ids_count = original_movies_metadata_df['id'].nunique()
print(f"Number of unique IDs: {unique_ids_count}")
print(f"Total number of rows: {len(original_movies_metadata_df)}")

Number of unique IDs: 45433
Total number of rows: 45466

In [34]:
duplicated_rows = original_movies_metadata_df[original_movies_metadata_df['id'].duplicated(keep=False)]
print("Duplicate IDs:")
print(duplicated_rows[['id']].sort_values('id'))

Duplicate IDs:
             id
5865     4912.0
33826    4912.0
9165     5511.0
7345     5511.0
44821   10991.0
...         ...
33184  298721.0
40040  298721.0
19730       NaN
29503       NaN
35587       NaN

[62 rows x 1 columns]

In [35]:
movies = movies.dropna(subset=['id'])
movies = movies.drop_duplicates(subset=['id'], keep='first')

unique_ids_count = movies['id'].nunique()
print(f"Number of unique IDs: {unique_ids_count}")
print(f"Total number of rows: {len(movies)}")

Number of unique IDs: 45432
Total number of rows: 45432

In [41]:
unique_titles_count = movies['title'].nunique()
print(f"Number of unique titles: {unique_titles_count}")
print(f"Total number of rows: {len(movies)}")

Number of unique titles: 42276
Total number of rows: 45432

In [42]:
movies = movies.dropna(subset=['title'])
movies = movies.drop_duplicates(subset=['title'], keep='first')

In [43]:
unique_titles_count = movies['title'].nunique()
print(f"Number of unique titles: {unique_titles_count}")
print(f"Total number of rows: {len(movies)}")

Number of unique titles: 42276
Total number of rows: 42276

In [29]:
movies['cast'].iloc[0]

"[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]"

In [30]:
original_keywords_df['keywords'].iloc[0]

"[{'id': 931, 'name': 'jealousy'}, {'id': 4290, 'name': 'toy'}, {'id': 5202, 'name': 'boy'}, {'id': 6054, 'name': 'friendship'}, {'id': 9713, 'name': 'friends'}, {'id': 9823, 'name': 'rivalry'}, {'id': 165503, 'name': 'boy next door'}, {'id': 170722, 'name': 'new toy'}, {'id': 187065, 'name': 'toy comes to life'}]"

In [55]:
movies.head()

,id,title,genres,overview,popularity,release_date,tagline,cast,crew,keywords,vote_average,vote_count
1,8844.0,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,Roll the dice and unleash the excitement!,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",6.9,2413.0
2,15602.0,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,11.7129,1995-12-22,Still Yelling. Still Fighting. Still Ready for...,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",6.5,92.0
3,31357.0,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,Friends are the people who let you be yourself...,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",6.1,34.0
4,11862.0,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,8.387519,1995-02-10,Just When His World Is Back To Normal... He's ...,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",5.7,173.0
5,949.0,Heat,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...","Obsessive master thief, Neil McCauley leads a ...",17.924927,1995-12-15,A Los Angeles Crime Saga,"[{'cast_id': 25, 'character': 'Lt. Vincent Han...","[{'credit_id': '52fe4292c3a36847f802916d', 'de...","[{'id': 642, 'name': 'robbery'}, {'id': 703, '...",7.7,1886.0

In [63]:
movies['crew'].iloc[0]

"[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'department': 'Production', 'gender': 2, 'id': 511, 'job': 'Executive Producer', 'name': 'Larry J. Franco', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7c89', 'department': 'Writing', 'gender': 2, 'id': 876, 'job': 'Screenplay', 'name': 'Jonathan Hensleigh', 'profile_path': '/l1c4UFD3g0HVWj5f0CxXAvMAGiT.jpg'}, {'credit_id': '52fe44bfc3a36847f80a7cdd', 'department': 'Sound', 'gender': 2, 'id': 1729, 'job': 'Original Music Composer', 'name': 'James Horner', 'profile_path': '/oLOtXxXsYk8X4qq0ud4xVypXudi.jpg'}, {'credit_id': '52fe44bfc3a36847f80a7c7d', 'department': 'Directing', 'gender': 2, 'id': 4945, 'job': 'Director', 'name': 'Joe Johnston', 'profile_path': '/fok4jaO62v5IP6hkpaaAcXuw2H.jpg'}, {'credit_id': '52fe44bfc3a36847f80a7cd7', 'department': 'Editing', 'gender': 2, 'id': 4951, 'job': 'Editor', 'name': 'Robert Dalva', 'profile_path': None}, {'credit_id': '573523bec3a368025100062c', 'department': 'Production', 'gender': 0, 'id': 4952, 'job': 'Casting', 'name': 'Nancy Foy', 'profile_path': '/blCkmS4dqNsbPGuQfozHE6wgWBw.jpg'}, {'credit_id': '5722a924c3a3682d1e000b41', 'department': 'Visual Effects', 'gender': 0, 'id': 8023, 'job': 'Animation Supervisor', 'name': 'Kyle Balda', 'profile_path': '/jR8iAP6uC0V42KbUG87qBIUO3Hj.jpg'}, {'credit_id': '52fe44c0c3a36847f80a7ce3', 'department': 'Art', 'gender': 2, 'id': 9967, 'job': 'Production Design', 'name': 'James D. Bissell', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7cb9', 'department': 'Production', 'gender': 2, 'id': 9184, 'job': 'Producer', 'name': 'Scott Kroopf', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7ccb', 'department': 'Production', 'gender': 2, 'id': 9196, 'job': 'Executive Producer', 'name': 'Ted Field', 'profile_path': '/qmB7sZcgRUq7mRFBSTlSsVXh7sH.jpg'}, {'credit_id': '52fe44bfc3a36847f80a7cc5', 'department': 'Production', 'gender': 2, 'id': 18389, 'job': 'Executive Producer', 'name': 'Robert W. Cort', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7cbf', 'department': 'Camera', 'gender': 2, 'id': 11371, 'job': 'Director of Photography', 'name': 'Thomas E. Ackerman', 'profile_path': '/xFDbxk53icM1ofL4iCIwB4GkUxN.jpg'}, {'credit_id': '52fe44bfc3a36847f80a7c83', 'department': 'Writing', 'gender': 2, 'id': 42356, 'job': 'Novel', 'name': 'Chris van Allsburg', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7cb3', 'department': 'Production', 'gender': 2, 'id': 42357, 'job': 'Producer', 'name': 'William Teitler', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7c8f', 'department': 'Writing', 'gender': 2, 'id': 56520, 'job': 'Screenplay', 'name': 'Greg Taylor', 'profile_path': None}, {'credit_id': '52fe44bfc3a36847f80a7c95', 'department': 'Writing', 'gender': 2, 'id': 56521, 'job': 'Screenplay', 'name': 'Jim Strain', 'profile_path': None}]"

In [36]:
def clean_strings(node_string, properties):
    if node_string is None or pd.isna(node_string):
        return None
        
    data = ast.literal_eval(node_string)
    
    for item in data:
        for key in properties:
            if key in item:
                if item[key] is None:
                    item[key] = 'None'
                else:
                    item[key] = item[key].replace("'", "\\'")
                    item[key] = item[key].replace("\"", "")
                    item[key] = item[key].replace("\u00A0", " ")
                    item[key] = item[key].replace("\x92", "\\'")
                    item[key] = item[key].replace("\xad", "-")
    
    return data

movies['keywords'] = movies['keywords'].apply(clean_strings, properties=['name'])
movies['crew'] = movies['crew'].apply(clean_strings, properties=['name', 'job', 'profile_path'])
movies['cast'] = movies['cast'].apply(clean_strings, properties=['name', 'character', 'profile_path'])

In [44]:
output_path = r"..\output\normalized_movies_data_part"
os.makedirs(os.path.dirname(output_path), exist_ok=True)
for i, chunk in enumerate(np.array_split(movies, 10)):
    chunk.to_csv(f'{output_path}_{i}.csv', index=False, encoding='utf-8')

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [38]:
movies.shape

(45432, 14)

In [39]:
movies.head()

,id,title,genres,overview,popularity,release_date,tagline,cast,crew,keywords,vote_average,vote_count,poster_path,imdb_id
0,862.0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",7.7,5415.0,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,tt0114709
1,8844.0,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,Roll the dice and unleash the excitement!,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",6.9,2413.0,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,tt0113497
2,15602.0,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,11.7129,1995-12-22,Still Yelling. Still Fighting. Still Ready for...,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",6.5,92.0,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,tt0113228
3,31357.0,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,Friends are the people who let you be yourself...,"[{'cast_id': 1, 'character': 'Savannah \'Vanna...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",6.1,34.0,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,tt0114885
4,11862.0,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,8.387519,1995-02-10,Just When His World Is Back To Normal... He's ...,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",5.7,173.0,/e64sOI48hQXyru7naBFyssKFxVd.jpg,tt0113041